# SIT -System Integrations Test,

server:
  port: 9876

spring:
  application:
    name: Mapeamentos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mappings?createDatabaseIfNotExist=true
    username: ${name}
    password: ${pwd}

  #JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    open-in-view: false
  security:
    user:
      name: entity
      password: entity